// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// let2base_c
int let2base_c(String letter, CharacterVector alph_vect);
RcppExport SEXP kmermods_let2base_c(SEXP letterSEXP, SEXP alph_vectSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< String >::type letter(letterSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type alph_vect(alph_vectSEXP);
    __result = Rcpp::wrap(let2base_c(letter, alph_vect));
    return __result;
END_RCPP
}
// base5to10_c
int base5to10_c(NumericVector number, int k, int base);
RcppExport SEXP kmermods_base5to10_c(SEXP numberSEXP, SEXP kSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type number(numberSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    __result = Rcpp::wrap(base5to10_c(number, k, base));
    return __result;
END_RCPP
}
